<a href="https://colab.research.google.com/github/marcocintra/Atmosphere/blob/master/F10_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Download F10_7_fluxtable.txt from https://doi.org/10.5281/zenodo.15453941

In [4]:
import matplotlib.pyplot as plt
import pandas as pd

def convert_to_datetime(date_str, time_str):
    return pd.to_datetime(date_str + time_str, format='%Y%m%d%H%M%S')

data = []
with open('fluxtable.txt') as file:
    next(file)
    next(file)
    for line in file:
        if line.startswith('-'):
            continue
        parts = line.split()
        if len(parts) < 7:
            continue
        flux_date = parts[0]
        flux_time = parts[1]
        flux_obs_flux = float(parts[4])
        flux_adj_flux = float(parts[5])
        datetime = convert_to_datetime(flux_date, flux_time)
        data.append((datetime, flux_obs_flux, flux_adj_flux))

df = pd.DataFrame(data, columns=['datetime', 'fluxobsflux', 'fluxadjflux'])

start_date = '2022-01-01'
end_date = '2024-12-31'
mask = (df['datetime'] >= start_date) & (df['datetime'] <= end_date)
filtered_df = df.loc[mask]

In [5]:
df

                 datetime  fluxobsflux  fluxadjflux
0     2004-10-28 17:00:00        132.7        130.9
1     2004-10-28 20:00:00        135.8        134.0
2     2004-10-29 20:00:00        130.6        128.8
3     2004-10-29 23:00:00        134.2        132.3
4     2004-10-30 17:00:00        147.9        145.8
...                   ...          ...          ...
22206 2025-02-12 22:00:00        168.5        164.2
22207 2025-02-13 18:00:00        170.2        166.0
22208 2025-02-13 20:00:00        173.4        169.0
22209 2025-02-13 22:00:00        176.8        172.4
22210 2025-02-14 18:00:00        177.5        173.1

[22211 rows x 3 columns]

In [6]:
filtered_df

                 datetime  fluxobsflux  fluxadjflux
18780 2022-01-01 18:00:00         94.8         91.7
18781 2022-01-01 20:00:00         93.9         90.8
18782 2022-01-01 22:00:00         93.3         90.2
18783 2022-01-02 18:00:00         90.1         87.1
18784 2022-01-02 20:00:00         89.0         86.0
...                   ...          ...          ...
22071 2024-12-29 20:00:00        254.7        246.3
22072 2024-12-29 22:00:00        252.1        243.8
22073 2024-12-30 18:00:00        223.9        216.5
22074 2024-12-30 20:00:00        223.5        216.1
22075 2024-12-30 22:00:00        222.8        215.5

[3296 rows x 3 columns]

In [7]:
import pandas as pd

filtered_df = filtered_df.copy()
filtered_df['datetime'] = pd.to_datetime(filtered_df['datetime'])

start_date = '2022-03-01'
end_date = '2024-12-31'
period_df = filtered_df[(filtered_df['datetime'] >= start_date) &
                         (filtered_df['datetime'] <= end_date)]

In [8]:
period_df

                 datetime  fluxobsflux  fluxadjflux
18957 2022-03-01 17:00:00         99.6         97.8
18958 2022-03-01 20:00:00         99.3         97.5
18959 2022-03-01 23:00:00        104.0        102.1
18960 2022-03-02 17:00:00        107.2        105.4
18961 2022-03-02 20:00:00        109.5        107.6
...                   ...          ...          ...
22071 2024-12-29 20:00:00        254.7        246.3
22072 2024-12-29 22:00:00        252.1        243.8
22073 2024-12-30 18:00:00        223.9        216.5
22074 2024-12-30 20:00:00        223.5        216.1
22075 2024-12-30 22:00:00        222.8        215.5

[3119 rows x 3 columns]

In [9]:
mask = period_df['datetime'].dt.hour.isin([22, 23])
df_22_23 = period_df[mask]

media_fluxo = df_22_23['fluxobsflux'].mean()
print(f"Average flow for 22:00 and 23:00: {media_fluxo}")

Average flow for 22:00 and 23:00: 160.96753121998077

In [10]:
print("Top 10 fluxobsflux values:")
top10_obs = period_df.sort_values(by='fluxobsflux', ascending=False).head(10)
print(top10_obs)

print("\nTop 10 fluxadjflux values:")
top10_adj = period_df.sort_values(by='fluxadjflux', ascending=False).head(10)
print(top10_adj)

seasonal_df = period_df[period_df['datetime'].dt.month.isin([3, 6, 9, 12])]

print("Top 10 fluxobsflux values (filtered months):")
top10_obs = seasonal_df.sort_values(by='fluxobsflux', ascending=False).head(10)
print(top10_obs)

print("\nTop 10 fluxadjflux values (filtered months):")
top10_adj = seasonal_df.sort_values(by='fluxadjflux', ascending=False).head(10)
print(top10_adj)

december_2024_df = period_df[(period_df['datetime'].dt.month == 12) &
                             (period_df['datetime'].dt.year == 2024)]

september_2024_df = period_df[(period_df['datetime'].dt.month == 9) &
                             (period_df['datetime'].dt.year == 2024)]

print("\nTop 10 fluxobsflux values (december/2024):")
top10_obs_dec = december_2024_df.sort_values(by='fluxobsflux', ascending=False).head(10)
print(top10_obs_dec)

print("\nTop 10 fluxadjflux values (december/2024):")
top10_adj_dec = december_2024_df.sort_values(by='fluxadjflux', ascending=False).head(10)
print(top10_adj_dec)

print("\nTop 10 fluxobsflux values (september/2024):")
top10_obs_sep = september_2024_df.sort_values(by='fluxobsflux', ascending=False).head(10)
print(top10_obs_sep)

print("\nTop 10 fluxadjflux values (september/2024):")
top10_adj_sep = september_2024_df.sort_values(by='fluxadjflux', ascending=False).head(10)
print(top10_adj_sep)

Top 10 fluxobsflux values:
                 datetime  fluxobsflux  fluxadjflux
20927 2023-12-14 18:00:00        852.3        825.9
21615 2024-07-30 20:00:00        400.7        412.9
19501 2022-08-29 17:00:00        357.1        364.2
20027 2023-02-17 20:00:00        343.1        335.0
21642 2024-08-08 20:00:00        336.0        345.4
21808 2024-10-03 17:00:00        316.9        317.2
21646 2024-08-09 23:00:00        316.1        324.7
21810 2024-10-03 20:00:00        311.9        312.1
21811 2024-10-03 23:00:00        311.7        311.9
21814 2024-10-04 23:00:00        306.8        306.8

Top 10 fluxadjflux values:
                 datetime  fluxobsflux  fluxadjflux
20927 2023-12-14 18:00:00        852.3        825.9
21615 2024-07-30 20:00:00        400.7        412.9
19501 2022-08-29 17:00:00        357.1        364.2
21642 2024-08-08 20:00:00        336.0        345.4
20027 2023-02-17 20:00:00        343.1        335.0
21646 2024-08-09 23:00:00        316.1        324.7
21808 2024-10-03 17:00:00        316.9        317.2
21645 2024-08-09 20:00:00        305.5        313.9
21644 2024-08-09 17:00:00        305.1        313.5
21643 2024-08-08 23:00:00        304.7        313.2
Top 10 fluxobsflux values (filtered months):
                 datetime  fluxobsflux  fluxadjflux
20927 2023-12-14 18:00:00        852.3        825.9
20641 2023-09-09 23:00:00        274.6        278.6
22057 2024-12-24 22:00:00        265.5        256.8
22069 2024-12-28 22:00:00        262.8        254.1
21722 2024-09-04 20:00:00        261.8        266.2
22066 2024-12-27 22:00:00        260.8        252.3
22068 2024-12-28 20:00:00        260.3        251.8
22070 2024-12-29 18:00:00        260.0        251.5
22065 2024-12-27 20:00:00        258.5        250.0
22056 2024-12-24 20:00:00        258.5        250.1

Top 10 fluxadjflux values (filtered months):
                 datetime  fluxobsflux  fluxadjflux
20927 2023-12-14 18:00:00        852.3        825.9
20641 2023-09-09 23:00:00        274.6        278.6
21722 2024-09-04 20:00:00        261.8        266.2
22057 2024-12-24 22:00:00        265.5        256.8
22069 2024-12-28 22:00:00        262.8        254.1
21723 2024-09-04 23:00:00        249.6        253.8
21728 2024-09-06 20:00:00        248.9        252.8
21727 2024-09-06 17:00:00        248.9        252.8
22066 2024-12-27 22:00:00        260.8        252.3
22068 2024-12-28 20:00:00        260.3        251.8

Top 10 fluxobsflux values (december/2024):
                 datetime  fluxobsflux  fluxadjflux
22057 2024-12-24 22:00:00        265.5        256.8
22069 2024-12-28 22:00:00        262.8        254.1
22066 2024-12-27 22:00:00        260.8        252.3
22068 2024-12-28 20:00:00        260.3        251.8
22070 2024-12-29 18:00:00        260.0        251.5
22056 2024-12-24 20:00:00        258.5        250.1
22065 2024-12-27 20:00:00        258.5        250.0
22062 2024-12-26 20:00:00        255.8        247.4
22071 2024-12-29 20:00:00        254.7        246.3
22063 2024-12-26 22:00:00        254.2        245.9

Top 10 fluxadjflux values (december/2024):
                 datetime  fluxobsflux  fluxadjflux
22057 2024-12-24 22:00:00        265.5        256.8
22069 2024-12-28 22:00:00        262.8        254.1
22066 2024-12-27 22:00:00        260.8        252.3
22068 2024-12-28 20:00:00        260.3        251.8
22070 2024-12-29 18:00:00        260.0        251.5
22056 2024-12-24 20:00:00        258.5        250.1
22065 2024-12-27 20:00:00        258.5        250.0
22062 2024-12-26 20:00:00        255.8        247.4
22071 2024-12-29 20:00:00        254.7        246.3
22063 2024-12-26 22:00:00        254.2        245.9

Top 10 fluxobsflux values (september/2024):
                 datetime  fluxobsflux  fluxadjflux
21722 2024-09-04 20:00:00        261.8        266.2
21723 2024-09-04 23:00:00        249.6        253.8
21727 2024-09-06 17:00:00        248.9        252.8
21728 2024-09-06 20:00:00        248.9        252.8
21721 2024-09-04 17:00:00        245.7        249.8
21712 2024-09-01 17:00:00        244.4        248.8
21729 2024-09-06 23:00:00        242.4        246.2
21719 2024-09-03 20:00:00        242.1        246.3
21725 2024-09-05 20:00:00        240.7        244.6
21720 2024-09-03 23:00:00        238.2        242.2

Top 10 fluxadjflux values (september/2024):
                 datetime  fluxobsflux  fluxadjflux
21722 2024-09-04 20:00:00        261.8        266.2
21723 2024-09-04 23:00:00        249.6        253.8
21727 2024-09-06 17:00:00        248.9        252.8
21728 2024-09-06 20:00:00        248.9        252.8
21721 2024-09-04 17:00:00        245.7        249.8
21712 2024-09-01 17:00:00        244.4        248.8
21719 2024-09-03 20:00:00        242.1        246.3
21729 2024-09-06 23:00:00        242.4        246.2
21725 2024-09-05 20:00:00        240.7        244.6
21720 2024-09-03 23:00:00        238.2        242.2

In [13]:
data_filtrada = filtered_df[filtered_df['datetime'].dt.strftime('%Y-%m-%d') == '2024-09-26']

pd.set_option('display.max_rows', None)

print("Flux values ​​for 09/26/2024:")
print(data_filtrada)

Flux values ​​for 09/26/2024:
                 datetime  fluxobsflux  fluxadjflux
21787 2024-09-26 17:00:00        182.5        183.4
21788 2024-09-26 20:00:00        181.1        182.0
21789 2024-09-26 23:00:00        182.7        183.5

In [14]:
data_filtrada = filtered_df[filtered_df['datetime'].dt.strftime('%Y-%m-%d') == '2024-09-27']

pd.set_option('display.max_rows', None)

print(" values ​​for 09/27/2024:")
print(data_filtrada)

 values ​​for 09/27/2024:
                 datetime  fluxobsflux  fluxadjflux
21790 2024-09-27 17:00:00        187.3        188.1
21791 2024-09-27 20:00:00        186.0        186.7
21792 2024-09-27 23:00:00        188.7        189.5